### ISSUE TITLE
Registrierung Vorname + Nachname hinzufügen 

### ISSUE THREAD

**Issue by CGreweling** [virtUOS/studip-ohn#102]
Im Registrierungsformular Feld Vorname und Feld Nachnahme als Pflichtfelder hinzufügen.

**Comment by luniki** [comment]
Ist das nicht eine Einstellungssache auf dem konkreten Server? Im Mooc.IP-Plugin kann ich das nicht vorgeben. AFAIK konfiguriert man das in seiner Stud.IP-Instanz.

**Comment by tthelen** [comment]
Frage: Kann bisheriges Datenfeld (vollst. Name) weg? Konsequenz: Echter Name der Nutzer ist nicht mehr bekannt (z.B. für Zertifikate).

Vor- und Nachname kann für beliebig gewählten Namen genutzt werden.

**Comment by lkiesow** [comment]
- Vollständiger Name ist gewünscht (kann nicht weg)
- Vor-/Nachname (Psedonym als Zusatzfeld)

**Comment by CGreweling** [comment]
![register](https://cloud.githubusercontent.com/assets/3499600/7453131/4eec8550-f266-11e4-925d-4e5173bbda99.png)

@lkiesow ok so?

**Comment by CGreweling** [comment]
OK. So eingefügt, Vollständiger Name ist auf wunsch pflichtfeld
