### ISSUE TITLE
Teilnehmerliste exportieren schlägt fehl

### ISSUE THREAD

**Issue by CGreweling** [virtUOS/studip-ohn#103]
Fatal error: Call to undefined function xslt_create() in /export_run_xslt.inc.php on line 103

**Comment by luniki** [comment]
Da muss auf dem System u.a. XSLT installiert werden. Siehe Installationsanleitung: https://develop.studip.de/trac/export/33955/branches/3.1/doc/de/studip-installation-guide-de310.pdf

**Comment by CGreweling** [comment]
ah besten dank,
funktioniert
