### ISSUE TITLE
Cronjob öffnet sporadisch Kurse vor Ihrem Startdatum

### ISSUE THREAD

**Issue by CGreweling** [virtUOS/studip-ohn#105]
Handwerkszeug studieren Start 15.06
Mathe Ingenuerwisscheschaften start 02.06
Mathe wiwi Start 16.11
Stand 20.05.2015 werden jetzt  durch den Cronjob von Vorläufig eintragen auf Direkt eintragen geändert....
habe den vorläufig deaktiviert.
@lkiesow bitte auch ein Auge drauf haben, dass die passend frei-geschaltet sind

**Comment by CGreweling** [comment]
in 
preliminary_participants.php 
muss glaub ich 
Z:70:           unset($course);
mit in die übergeordnete If-Abfrage. Leider kann ich das lokal gerade nicht testen.

**Comment by tgloeggl** [comment]
Nein, es müssen die Zeilen

```
$course->admission_prelim = 0;
$course->store();
```

mit in die If-Abfrage, d.h. das darf nur geändert werden, wenn der Kurs tatsächlich schon begonnen hat. Hatte ich falsch platziert.

**Comment by tgloeggl** [comment]
fixed in https://github.com/virtUOS/mooc.ip/commit/97aaafe3d4d8505c7d49254782c85b8f3b54687b
