### ISSUE TITLE
Teilnehmer-Startseite aufräumen

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/studip-ohn#107]
- Linke Seite: Sprungmarken weg
- OHN widget: Schließen-Link weg
- Stattdessen wie sidebar edx
- Dozenten sollen gleiche Ansicht haben

Das löst vermutlich auch:
https://github.com/virtUOS/studip-ohn/issues/106

**Comment by CGreweling** [comment]
Per Java Script ausblenden ist OK.
So sieht es bei EDx aus. 
![sidebar](https://cloud.githubusercontent.com/assets/3499600/8427338/be9a8a8c-1f16-11e5-9fbf-fade4d9b4bd1.png)

**Comment by rlucke** [comment]
So eine Darstellung ist mit einem Widget aber wohl nicht möglich oder irre ich mich da?!
Somit müsste das ganze auch per Javascript eingebunden werden.

**Comment by CGreweling** [comment]
@rlucke muss ich dafür noch irgendetwas auslösen? mit einem reinem Git update sehe ich keine Veränderung

**Comment by rlucke** [comment]
Eigentlich sollten die Änderungen in application.js die Sidebar Widgets ausblenden und neue Elemente einfügen. Änderungen im Header Template stellen die Nutzerinformationen bereit.

**Comment by CGreweling** [comment]
"Eigentlich" ;) 
es tut aber faktisch bei mir und im ohn-kursportal nicht.

**Comment by rlucke** [comment]
Falsche Klammerung behoben; Harte Verlinkung entfernt; Username zentriert;
