### ISSUE TITLE
Block 1762: Tabelle defekt

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/studip-ohn#110]
Durch den Bücherdschungel -> lesen und excerpieren -> excerpieren -> block 1762
- Breite wird nicht beibehalten
- Solider schwarzer Rahmen

![tab](https://cloud.githubusercontent.com/assets/1008395/8405380/51ff17b6-1e54-11e5-90e0-b0bac3ffe09a.png)

**Comment by luhcas** [comment]
Was stimmt mit der Breite nicht? Soll der Rahmen ganz weg?

**Comment by lkiesow** [comment]
- Rahmen ganz weg
- Breite stimmt nicht mit dem WYSIWYG-Editor überein. Da kannst du nicht direkt etwas machen. Etwas padding links und rechts wäre aber vermutlich schon hilfreich.

**Comment by lkiesow** [comment]
Nun sind die Rahmen zwar weg, aber leider auch die komplette zweite Spalte mit den Kästen.

**Comment by lkiesow** [comment]
Gefixt mit ein paar &nbsp
