### ISSUE TITLE
Einrückung von Courseware übernehmen

### ISSUE THREAD

**Issue by tthelen** [virtUOS/studip-ohn#113]
Der wundervollen Code für das Lieblingsfeature ++ in MOOC.IP übernehmen

**Comment by luniki** [comment]
Siehe virtUOS/mooc.ip#378

**Comment by luniki** [comment]
Das Feature ist als Branch in virtUOS/mooc.ip eingebaut. @CGreweling testet und merged das noch.

**Comment by CGreweling** [comment]
ist gemerged und als update installiert
