### ISSUE TITLE
VIPS: Kopieren funktioniert nicht mehr. Aufgaben verschwunden

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/studip-ohn#117]
- Ich bin im Handw.-Vips
- Will eine Aufgabenblatt kopieren
  - Beim direkten Kopieren bekomme ich einen Fehler (kein Zugriff)
  - Beim kopieren am Ende der Seite werden nur noch Vips von
    „M zur I 2015“ angezeigt. Alle anderen
    Aufgabenblätter fehlen.

**Comment by CGreweling** [comment]
Ich würde mal vermuten, dass der root-account nicht mit den vips verknüpft ist...
In Mathe ist der root komischerweise eingetragen.

**Comment by CGreweling** [comment]
Mit Vips Version 1.1 sind Vips direkt einem Kurs zugeordnet, Sie dürfen nur von dozenten dieses Kurses verändert werden. Dass root das nicht darf ist gerade nich ein Bug, wird Elmar behoben.
Workaround -> eigenen Account als Dozent/Tutor eintragen.
