### ISSUE TITLE
„Nächster Block“ funktioniert nicht immer

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/studip-ohn#118]
Teilweise wird man auf einen falschen Block verwiesen..

Beispiel:

HZ -> „Ordnung schaffen“ -> „Arbeitsplatz Bibliothek“ -> Erster Block: Nach rechts Pfeil/Nächster Block verweist auf „Arbeitsplatz Bibliothek III“.

**Comment by CGreweling** [comment]
neu sortieren?
