### ISSUE TITLE
Css Navigation Chapter/Subchapter "display: inline-block;" hinzufügen

### ISSUE THREAD

**Issue by CGreweling** [virtUOS/studip-ohn#119]

**Comment by luhcas** [comment]
Kannst du mir einen Screenshot schicken? Bei mir sieht alles normal aus

**Comment by CGreweling** [comment]
@luhcas wie siehts damit aus?

**Comment by luhcas** [comment]
@CGreweling ich brauche einen Screenshot. Weiß noch nicht was du meinst.

**Comment by CGreweling** [comment]
Beispiel:
![einrucken](https://cloud.githubusercontent.com/assets/3499600/8517557/6907c20a-23c2-11e5-978c-41a82b0dfb06.png)
"Ungerichtete Graphen" muss gleich weit eingerückt sein, dass ist eine Chapter überschrift

**Comment by luhcas** [comment]
<img width="297" alt="bildschirmfoto 2015-07-06 um 09 43 02" src="https://cloud.githubusercontent.com/assets/1556426/8517687/6e2ba098-23c3-11e5-9779-d453f9da403b.png">
Komisch. Bei mir sieht es so aus in Firefox, Chrome und Safari

**Comment by CGreweling** [comment]
Mit einem der letzen Patche ist die möglichkeit dazu gekommen, chapters ein zu rücken.
Schreibe mal vor ein chapter ein ++.
Das wird dann in ein oder zwei leerzeichen umgewandelt.
