### ISSUE TITLE
Zuordnungsaufgabe mit ungleich vielen Elementen

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/studip-ohn#120]
HZ -> ordnung schaffen -> Themenfindung -> Wörterbuch -> Wörterbuch II

4 von 6 Elementen müssen nur zogeordnet werden

**Comment by lkiesow** [comment]
Gleiches Problem bei: HZ -> Ordnung -> Korrektur II

**Comment by CGreweling** [comment]
tthelen hat eine Lösung mit Lückentext und Auswahlmenü als Alternative gebaut.
Kittel schaut sich das an, meldet sich falls im die Alternative nicht ausreicht.
