### ISSUE TITLE
oder Operator in Lückentext funktioniert nicht

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/studip-ohn#121]
```
 [[2|3|4]]     Vorgespräch mit DozentInnen, Themenmodifizierung, Hinweise aufnehmen   
```

2 wird als korrekt ausgewertet, 3 nicht:

![aaaaaaaaaaaaaaa](https://cloud.githubusercontent.com/assets/1008395/8435917/9e67ef3c-1f54-11e5-88f4-5ea523cabfaf.png)

**Comment by lkiesow** [comment]
HZ -> ordnung schaffen -> 21 schritte

**Comment by CGreweling** [comment]
Das ganze funktioniert in der Vips Vorschau. 
In Coursware nicht mehr,der oder operator wird anscheinend nicht beachtet,
auch bei der Lösungsanzeige werden Zahlen hinter dem | operator nicht dargestellt.
Die Formatierung ist auch nicht mehr korrekt.
@tgloeggl kennst du Dich mit der Einbung von Vips in courseware aus?

**Comment by tgloeggl** [comment]
parse and show correct answer possibilities 
https://github.com/virtUOS/mooc.ip/commit/1f13236b2ed09b28b96d6a487481799e4f4520fe
