### ISSUE TITLE
Formatierung Lückentext nicht korrekt

### ISSUE THREAD

**Issue by CGreweling** [virtUOS/studip-ohn#123]
HZ -> ordnung schaffen -> 21 schritte
siehe #121

**Comment by luhcas** [comment]
nach jeder Frage wird ein br-Tag eingefügt. Dieser muss entfernt werden.

<img width="466" alt="bildschirmfoto 2015-07-14 um 15 36 00" src="https://cloud.githubusercontent.com/assets/1556426/8674420/1e3956e4-2a3e-11e5-9def-c9957205c329.png">

**Comment by luniki** [comment]
Warum fügt ihr & nbsp; ein?

**Comment by lkiesow** [comment]
„ “ habe ich genutzt da sonst kein Abstand nach den Lücken angezeigt wurde. Habe es noch einmal umgeschrieben. Nun scheint es zu passen.
