### ISSUE TITLE
Kurskopien für Herbstsurchlauf

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/studip-ohn#124]
- Kurse kopieren
- Dozenten benachrichtigen
- Startseite anpassen

**Comment by lkiesow** [comment]
- Startseite passt
- Kursanmeldeseiten opiert
- Dozenten benachrichtigt, dass sie über Anmeldeseiten schauen

**Comment by CGreweling** [comment]
Startseite und Anmeldeseite hab ich am we erstellt....
-> Dozenten informieren, dass das kopieren der Inhalte noch ca. 2 Wochen dauert.

**Comment by lkiesow** [comment]
Dozenten haben die vage Aussage:
- Vermutlich irgendwann nächste Woche
- Wir melden uns

**Comment by CGreweling** [comment]
Kurskopie abgeschlossen.
@lkiesow wie besprochen eine kurze mail an Dozenten

**Comment by lkiesow** [comment]
Mail an Dozenten ist raus
