### ISSUE TITLE
Lückentextaufgaben: Zeilenumbrüche Falsch

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/studip-ohn#128]
Aus

![aaaaaaaaaaaaaaa](https://cloud.githubusercontent.com/assets/1008395/8649057/ba818ca2-2966-11e5-89e2-aae2232826ba.png)

wird

![bbbbbbbbbbbbbbbbb](https://cloud.githubusercontent.com/assets/1008395/8649071/ce9712de-2966-11e5-8993-b077a43fbc89.png)

Offensichtlicherweise stimmt dort etwas mit den Zeilenumbrüchen nicht. Wo kommen die Leerzeilen her?

HZ -> Bücherdschungel -> Literaturrech.

**Comment by luniki** [comment]
In der Originalaufgabe sind &nbsp; enthalten:

```
string(553) "Suchen Sie folgendes Werk im Onlinekatalog der Bibliothek Bauwesen, Soziale Arbeit und Gesundheit der HAWK Hildesheim/Holzminden/G&ouml;ttingen und erg&auml;nzen Sie die fehlenden Daten:


Herausgeber &nbsp; &nbsp; [[Ullrich Bauer]] &nbsp; &nbsp;
Herausgeber     [[Uwe H. Bittlingmayer]]
Herausgeber     [[Albert Scherr]]
Titel     Handbuch Bildungs- und Erziehungssoziologie   &nbsp;
Erscheinungsort     [[Wiesbaden]]   &nbsp;
Erscheinungsjahr     2012   &nbsp;
Verlag     [[VS Verlag f&uuml;r Sozialwissenschaften]]   &nbsp;
ISBN     978-3-531-18944-4"
```

Das führt zu dem unterschiedlichen Verhalten.

**Comment by luniki** [comment]
Außerdem verhält sich die Courseware genauso, wie das auch Vips v1 täte. Hier mal ein Screenshot:

![selection_006](https://cloud.githubusercontent.com/assets/2993/8672004/3a4e09e2-2a2a-11e5-9889-f1fc8bac9aba.png)

**Comment by luniki** [comment]
Elmar hat AFAIK eine neue Ausgaberoutine, die dann in die Courseware integriert werden müsste. Dabei muss natürlich die Kompatibilität mit dem "alten" Vips erhalten bleiben.
