### ISSUE TITLE
Scrolling auf kurzen Seiten

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/studip-ohn#129]
![aaaaaaaaaaaaaaa](https://cloud.githubusercontent.com/assets/1008395/8649172/c48e19bc-2967-11e5-8c62-ca7373b13a7c.png)

Wie man sieht hat der Container mit dem Inhalt und der Navigation rechts eine Scrollbar die da nicht hin darf. Das Problem ist vermutlich, dass die Navigation höher ist als der Inhalt, die Höhe sich aber nur nach dem Inhalt richtet.

**Comment by CGreweling** [comment]
sieh nach Javascript-Fehler aus. nicht eilig

**Comment by luniki** [comment]
das ist ein reines css-problem...

**Comment by CGreweling** [comment]
okay, dann geht das an dich @luhcas
