### ISSUE TITLE
Bei Vips „Freie Antwort“ wird richtige Antwort nicht angezeigt

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/studip-ohn#131]
HZ -> Bücherdschungel -> Bibliotheksrecherche

![aaaaaaaaaaaaaaa](https://cloud.githubusercontent.com/assets/1008395/8649818/e27bba64-296d-11e5-8eac-99b87a1cdd10.png)

**Comment by tgloeggl** [comment]
fixed in https://github.com/virtUOS/mooc.ip/commit/31f1fafdfa9e4d58395682e1fa5da9d3f12fafbe
