### ISSUE TITLE
Zuordnungsaufgaben: Rahmen fehlt nach dem abschicken

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/studip-ohn#132]
![aaaaaaaaaaaaaaa](https://cloud.githubusercontent.com/assets/1008395/8650056/38057482-2970-11e5-8296-c53080c578c3.png)

Welche richtige  Antwort gehört wozu? Vor dem Abschicken war um die Blöcke ein Rahmen. So ist das ganze leider nicht mehr auseinanderzuhalten.

**Comment by luhcas** [comment]
Rahmen um einzelne Elemente
