### ISSUE TITLE
Tabellen funktionieren nicht in vips

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/studip-ohn#134]
Aufgabe:
![bbbbbbbbbbbbbbbb](https://cloud.githubusercontent.com/assets/1008395/8652239/2b285e9e-296d-11e5-9929-1bc4d25f35c1.png)

Anzeige:
![aaaaaaaaaaaaaaa](https://cloud.githubusercontent.com/assets/1008395/8652226/16f177c6-296d-11e5-9aff-6fd0aadbff0c.png)

Vips-Vorschau:
![cccccccccccccccc](https://cloud.githubusercontent.com/assets/1008395/8652274/4f4f143e-296d-11e5-863a-b2895e75ea23.png)

Die Tabellen werden an den Lücken beendet. Elmar sagt, es müsse das neue Vips-Template übernommen werden.

**Comment by lkiesow** [comment]
Achtung! Testaufgabe eingebaut in  _HZ -> Bücherdschungel -> Literaturrecherche I_

Muss wieder entfernt werden

**Comment by CGreweling** [comment]
@lkiesow ich finde das sieht jetzt ganz gut aus... was meinst du?

**Comment by lkiesow** [comment]
Scheint nun zu funktionieren.
