### ISSUE TITLE
„Neuer Abschnitt“-Text sollte placeholder sein nicht Inhalt

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/studip-ohn#138]
![aaaaaaaaaaaaaaa](https://cloud.githubusercontent.com/assets/1008395/8654447/a957e60a-298a-11e5-86ac-29ef77c6f48f.png)

So fängt man jedes mal an zu tippen und merkt dann, dass man noch den Text entfernen muss. Das Attribut „placeholder“ ist genau dafür gedacht.

**Comment by luniki** [comment]
Eigentlich soll es sich eher so verhalten, wie beim Anlegen eines neuen Ordners. Das ändere ich mal.
