### ISSUE TITLE
Quiz-Einrückung funktioniert nicht nach dem Abschicken

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/studip-ohn#139]
Aus
![aaaaaaaaaaaaaaa](https://cloud.githubusercontent.com/assets/1008395/8654696/569e1f90-298c-11e5-8b26-12cd5392521a.png)

wird nach dem Abschicken

![aaaaaaaaaaaaaaa](https://cloud.githubusercontent.com/assets/1008395/8654669/381bb5c8-298c-11e5-9ae4-ec2b37a0248f.png)

**Comment by lkiesow** [comment]
HZ -> wer hat's -> Quellennachweis I

**Comment by luhcas** [comment]
Fehler konnte ich nicht reproduzieren. Könnte sein, dass sich das durch #136 erledigt hat

**Comment by lkiesow** [comment]
Ist immer noch da, habe ich aber nun durch eine Tabelle ersetzt. War eh so gewünscht.
