### ISSUE TITLE
Navigation: Unicode funktioniert nicht

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/studip-ohn#142]
Unicode-Zeichen werden in HTML umgewandelt. Das wird dann wiederum escaped.

Resultat:
![aaaaaaaaaaaaaaa](https://cloud.githubusercontent.com/assets/1008395/8696189/d6188320-2ad9-11e5-9d5c-1e4351467ef9.png)

**Comment by luniki** [comment]
(Fast alle) Unicode-Zeichen werden in "numeric character references" umgewandelt. Das ist soweit normal. Was das "escapen" angeht, schau ich mal nach.
