### ISSUE TITLE
Lückentext: Lückenlänge

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/studip-ohn#144]
FRür die Zitate bräuchten wir längere Lücken:

![aaaaaaaaaaaaaaa](https://cloud.githubusercontent.com/assets/1008395/8696296/5cb70bc0-2aeb-11e5-9427-fb1868ecfdfe.png)

**Comment by CGreweling** [comment]
gerade sind die auf 174px auf 240px erhöhen, das sollte erstmal reichen?

**Comment by CGreweling** [comment]
@tgloeggl für den Fall das noch etwas Zeit über ist ;) siehe oben
