### ISSUE TITLE
Tabellen in Lückentexte einbauen

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/studip-ohn#145]
Depends on #134 

In diverse Lückentextaufgaben sollten Tabellen eingefügt werden. Beispiel:

![aaaaaaaaaaaaaaa](https://cloud.githubusercontent.com/assets/1008395/8696381/238d806c-2aec-11e5-82ad-213bd7875c43.png)

**Comment by lkiesow** [comment]
- Literaturrecherche
- Zitieren
- …

**Comment by CGreweling** [comment]
@lkiesow alles erledigt.
Bis auf VIPS Literaturreccherche III... wird die irgendwo verwendet?

**Comment by lkiesow** [comment]
Bin noch einmal durchgegangen. Sieht gut aus.
