### ISSUE TITLE
Text Box: Vorgegebener Text wird nicht angezeigt

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/studip-ohn#147]
In VIPS schon, in der Courseware nicht

**Comment by lkiesow** [comment]
Gibt es schon irgendein Update bei diesem Problem?
HAWK hat die Probleme bemerkt.

**Comment by tgloeggl** [comment]
Ist erledigt, da die Aufgabe jetzt auch direkt aus Vips kommt.
