### ISSUE TITLE
Textbox-Aufgaben: Größe passt nicht

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/studip-ohn#148]
![aaaaaaaaaaaaaaa](https://cloud.githubusercontent.com/assets/1008395/8718061/2e8a2ca8-2ba1-11e5-94d2-18b42d99d7c1.png)

Die Textbox ist sehr hoch, jedoch wird die Breite überhaupt nicht genutzt. 100% Beite und dafür nicht so hoch?

**Comment by luhcas** [comment]
Wie gelange ich zu dieser Ansicht?
