### ISSUE TITLE
Verstecken Wysiwyg-Ordner testen

### ISSUE THREAD

**Issue by tthelen** [virtUOS/studip-ohn#150]
Im Kurs Handwerkszeug soll jetzt:
- Der Ordner Wysiwyg für TN nicht sichtbar sein
- Alle dort hochgeladenen Dateien sollen aber korrekt angezeigt/runtergeladen werden können (s. Courseware-Inhalte)

**Comment by tthelen** [comment]
Allgemeine Anleitung:
- In der Veranstaltung über "+" die Dateiordnerberechtigungen einschalten
- Dann dem Ordner über "Bearbeiten" das Recht "Sichtbar (X)" entziehen

**Comment by CGreweling** [comment]
funktoniert!
