### ISSUE TITLE
Wysiwyg-Bug: Tabellen-Zellen-Hintergrund-Farbe verschwindet beim Editieren

### ISSUE THREAD

**Issue by tthelen** [virtUOS/studip-ohn#152]

**Comment by zabbarob** [comment]
siehe auch https://develop.studip.de/trac/ticket/4988

**Comment by zabbarob** [comment]
Ihr könnt den Fix in https://develop.studip.de/trac/changeset/34797 übernehmen um das zu beheben.

**Comment by CGreweling** [comment]
@zabbarob ich hab keinen account auf develop.studip...
wie bekomme ich den patch am besten in unser ohn studip?

**Comment by zabbarob** [comment]
Du musst nur in der `public/assets/javascripts/wysiwyg.js` die `background-color` für `td`-Elemente freigeben:

``` javascript
CKEDITOR.replace(textarea[0], {
  allowedContent: {
  ...
  td: {
    ...
    styles: ['text-align', 'width', 'height']
```

ändern zu

``` javascrip
    styles: ['text-align', 'width', 'height', 'background-color']
```

ungefähr Zeile 139.

Im HTMLPurifier müsste das schon freigeschaltet sein. Ansonsten in der `lib/classes/Markup.class.php` muss der Purifier konfiguriert sein mit:

``` php
$config->set('CSS.AllowedProperties', array(
    'margin-left',
    'text-align',
    'width',
    'height',
    'color',
    'background-color', // needed by span, td
    'float'
));
```

**Comment by CGreweling** [comment]
@zabbarob funktioniert leider nicht, kannst Du mir das mal zeigen, wenn Du im virtUOS bist?

**Comment by zabbarob** [comment]
Mit diesen beiden Änderungen sollte es tun. Evtl. muss noch ein "make squeeze" ausgeführt werden (Marcus dazu befragen). Ansonsten muss man sicherstellen dass nicht eine alte `wysiwyg.js` aus dem Browser-Cache geladen wird.

**Comment by CGreweling** [comment]
make squeeze und cache leeren ist die Lösung
