### ISSUE TITLE
Schriftgrößen und Schriftarten vereinheitlichen

### ISSUE THREAD

**Issue by tthelen** [virtUOS/studip-ohn#153]
Unterschiedliche Schriftarten und -größen bei:
- Absatztext und Aufzählungen
- Absatztext und Tabellentext
- Unterschiedlichen Überschriten (z.B. Diskussions-Block)

**Comment by CGreweling** [comment]
@luhcas sind davon alle punkte erledigt?

**Comment by lkiesow** [comment]
Habe das Problem bei „Bekanntmachen in der virtuellen Cafeteria“ gelößt. Es war eine Tabelle mit Header und der Header war Fett. Die Tabelle war nicht nötig. Daher sollte das nun an der Stelle passen. Kannst du dennoch mal einmal durch den Kurs schauen ob die Schrift nun so in Ordnung ist?
