### ISSUE TITLE
Aufgabe "Bibliotheksrecherche I" checken

### ISSUE THREAD

**Issue by tthelen** [virtUOS/studip-ohn#154]
https://ohn-kursportal.de/plugins.php/mooc/courseware?cid=9f7a4da33c49cd9e57d53a287a9117f7&selected=2405

Probleme:
- In der Überschrift soll nur "Weltmusik" fett
- Einzelaufgaben haben keinen Titel
- Was ist das da bei Aufgabe 1???

**Comment by CGreweling** [comment]
Studip Markup Formatierung für VIPs aufgabenblattbeschreibung hinzugefügt
