### ISSUE TITLE
Aufgabenstellung bei vielen Aufgaben verschwunden

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/studip-ohn#164]
Beispiel Ada Lovelace I.

So sieht es aus:
![aaaaaaaaaaaaaaa](https://cloud.githubusercontent.com/assets/1008395/9085282/a81b12dc-3b7b-11e5-8258-ce12343b2130.png)

Wo ist der Aufgabentext:
![bbbbbbbbbbbbbbb](https://cloud.githubusercontent.com/assets/1008395/9085286/baa5e9cc-3b7b-11e5-9f95-18e4ee7dfd9c.png)

**Comment by tgloeggl** [comment]
Da ist wohl noch ein Fehler im neuen Template. Kümmere ich mich drum.

**Comment by tgloeggl** [comment]
Konnte in meiner Testinstallation keinen Fehler finden. Welcher Kurs und welches Kapitel ist das denn?

[EDIT]
Das war wohl nur ein temporärer Fehler und ist mittlerweile behoben.

**Comment by lkiesow** [comment]
Gerade noch einmal geschaut: Jetzt ist die Beschreibung da. Christian hatte glaub ich noch etwas eingespielt. Eventuell ist das Problem damit behoben worden. Ich frage ihn gleich mal.
