### ISSUE TITLE
TextBox: Sonderzeichenproblem nach Abschicken

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/studip-ohn#166]
![aaaaaaaaaaaaaaa](https://cloud.githubusercontent.com/assets/1008395/9196497/272b25d0-402c-11e5-8c6f-d33b8e8ab9e4.png)

Das war aber nicht, was ich da eingetippt habe.

**Comment by tgloeggl** [comment]
Sollte nun behoben sein, da fehlte an passender Stelle ein studip_utf8decode.
