### ISSUE TITLE
Wysiwyg Editor Bilder frei positionieren nicht möglich

### ISSUE THREAD

**Issue by CGreweling** [virtUOS/studip-ohn#17]

**Comment by zabbarob** [comment]
Was genau ist damit gemeint? Der Editor unterstützt derzeit das Einfügen von Bildern an einer beliebigen Position im Text. Es wird jedoch nicht unterstützt, dass Text als Fließtext um eingefügte Bilder herumläuft. Der Hintergrund ist, dass der notwendige CSS-Style `float` zu einer Zerstörung der Bildschirmmaske im Stud.IP führt.

**Comment by CGreweling** [comment]
ja genau es geht mir um den Fließtext. Ganz genau muss ich ein Bild rechts vom Text einfügen und dabei auch die Größe skalieren. Das mit Tabellen zu machen geht zwar ist aber recht aufwändig. Vor allem das skalieren fehlt mir.

**Comment by CGreweling** [comment]
Änderungen im "html-Modus" werden nicht übernommen

**Comment by zabbarob** [comment]
Es wird alles an HTML was nicht zulässig ist rausgefiltert. Der Wysiwyg-Editor macht das selber schon teilweise aber spätestens bei der Darstellung wird vollständig gefiltert. Bilder zu skalieren sollte aber funktionieren (tut bei mir lokal). Ich habe dazu einfach die Image-Properties im Wysiwyg geöffnet und dort die Breite eingegeben.

![image-properties](https://cloud.githubusercontent.com/assets/419922/5758509/8116ea02-9cc6-11e4-99e5-974c5b0425c4.png)
