### ISSUE TITLE
Wysiwyg Nummerierung Liste keine Zahlen

### ISSUE THREAD

**Issue by CGreweling** [virtUOS/studip-ohn#19]
Bei Auswahl werden die Zahlen nicht dargestellt.

cid=188447855eb161012ff16727dda6af70&data%5BNaN%5D=tree&selected=1646#author

**Comment by zabbarob** [comment]
kannst du mir den vollständigen link geben? Nummerierungen funktionieren eigentlich. siehe z.b. http://develop.studip.de/studip/wiki.php?cid=a70c45ca747f0ab2ea4acbb17398d370&wiki_comments=icon&keyword=WysiwygTests

**Comment by luhcas** [comment]
Funktioniert das nun?

**Comment by CGreweling** [comment]
nein das funktioniert noch nicht

**Comment by luhcas** [comment]
erledigt
