### ISSUE TITLE
Pluginnamen und Url ändern

### ISSUE THREAD

**Issue by CGreweling** [virtUOS/studip-ohn#24]
/studip/ müsste weg
und die der name des Plugins so dass in der nicht mehr in der url auftaucht

**Comment by luniki** [comment]
Meinst du eine URL wie "plugins.php/mooc/courseware"? Dort soll "mooc" weg?

**Comment by CGreweling** [comment]
ich dachte das würde sich ändern, wenn der name des Plugins geändert wurde?

**Comment by luniki** [comment]
Im Plugin selbst wird unterschieden zwischen dem Klassennamen des Plugins und dem angezeigten Namen des Plugins. Letzteren zu ändern ist leicht. Um den Klassennamen zu ändern (der in der URL verwendet wird), muss der gesamte PHP- und JS-Code durchgegangen und evtl. geändert werden. 

Das kann man natürlich machen, mir ist nur nicht klar, ob es das wert ist. Das Plugin könnte dann auch nicht mehr wirklich als Mooc.IP beworben werden ;-)

**Comment by CGreweling** [comment]
okay, dann habe ich das letztens falsch verstanden. Da ist natürlich dann nur das ändern des Plugin-Namens wünschenswert.

**Comment by lkiesow** [comment]
Fertig. Es gibt einen virtuellen-Host für ohn-kursportal.de
