### ISSUE TITLE
Latex engine

### ISSUE THREAD

**Issue by CGreweling** [virtUOS/studip-ohn#29]

**Comment by CGreweling** [comment]
Studip nutzt [tex]..[/tex] als markup für Latex.
Das ist verarltet. Aktuelle wird vin Mathjax /(../) als Standard verwendet so auch in edX

**Comment by zabbarob** [comment]
das kann man Mathjax aber sagen, was es verwenden soll. m.a.w. sollte [tex] mit egal welcher mathjax version funktionieren. umgekehrt könnte man stud.ip auch abgewöhnen [tex] zu verwenden ...oder evtl angewöhnen beides zu nehmen. dazu müsste dann aber ein plugin (moocip? ;-) ) das entsprechend im stud.ip konfigurieren. bzw. falls es hartkodiert ist, dann müsste stud.ip entsprechend erweitert werden

**Comment by CGreweling** [comment]
man kann studip über das Mathjax Plugin beibringen beides zu akzeptieren. Habe ich jetzt auch so gemacht. Aber dann ist natürlich die Frage was passiert bei einem Studip update. Muss ich das danach wieder nachpflegen oder wird die config nicht aktualisiert. Ich weiß das ist nix schwerwiegendes.
