### ISSUE TITLE
Welche Browser untertützen wir

### ISSUE THREAD

**Issue by CGreweling** [virtUOS/studip-ohn#31]
Welche Browser werden von Stduip/Mooc.ip unterstützt?
Firefox, IE, Chrome?

**Comment by tthelen** [comment]
Grundsätzlich werden alle modernen Browser in akutellen Versionen unterstützt, d.h. Chrome, Firefox, Safari und AKTUELLE Internet Explorer, d.h. mindestens IE 9.
