### ISSUE TITLE
Dateien Upload Vorschaubilder

### ISSUE THREAD

**Issue by CGreweling** [virtUOS/studip-ohn#33]
Wo sollen die Vorschaubilder und das Vorschau video hochgeladen werden?
Stichwort Kursübersichtsseite.
Ich kann zwar einen Link angeben, aber wo hin mit den Dateien.
Im Reiter "Dateien" würde man alles auch direkt den Studieren als Download anbieten, z.B. Teaser und Passbild(Kursautoren) ist das sinnvoll?

**Comment by tthelen** [comment]
Entweder statisch ablegen oder in den Dateibereich einer Einrichtung, die sind immer für alle lesbar und keiner stolpert drüber..

**Comment by CGreweling** [comment]
Ok. Das bedeutet natürlich im unkerhschluss dass solche Dateien nur durch den Admin eingebunden werden können. Da ich dachte, dass man die autoren nicht an das "kern"-Studip System ran lassen muss.
Ich mach das jetzt erstmal so

**Comment by CGreweling** [comment]
öffentlicher Dateiupload erstellt
