### ISSUE TITLE
BildFormatierungs Tags Kursübersichstsseite ohne funktion

### ISSUE THREAD

**Issue by CGreweling** [virtUOS/studip-ohn#34]
Man kann in den Grunddaten eines Kurse im Wysiwyg-Editor Größen eingeben. In der Vorschau funktionierts. Auf der "Übersicht"-Seite nicht.

**Comment by luniki** [comment]
Das liegt an diesem Stück LESS-Code:

https://github.com/virtUOS/mooc.ip/blob/9e6a37421f17e014b3c84596b4d4446eedf5ce2f/assets/style.less#L42

Mir ist nicht ganz klar, warum das so generisch enthalten ist. Das kam damals von Lucas rein:
https://github.com/virtUOS/mooc.ip/commit/7aef5204bc23c4dd7503e8edb74b2bb14d6282c5#diff-0

**Comment by luniki** [comment]
Ich nehm das erst mal halb raus und frag mal @luhcas was er genau damit erreichen wollte.

**Comment by luniki** [comment]
@luhcas Kannst du mal kurz auf https://github.com/virtUOS/mooc.ip/commit/7aef5204bc23c4dd7503e8edb74b2bb14d6282c5#diff-0 schauen? Dort werden alle img-Elemente auf "width: 100%;" gesetzt. Wofür?

**Comment by luhcas** [comment]
kann raus
