### ISSUE TITLE
Layout Kursübersichtsseite

### ISSUE THREAD

**Issue by CGreweling** [virtUOS/studip-ohn#43]
Die Infobox sieht ohne Rahmen recht verloren aus. Ideen dazu?
Das Feld Voraussetzungen sollte links unter die info-box oder unter den Beschreibungstext. 
So ist der Beschreibungstext bei der Länge zu schmal.

**Comment by luhcas** [comment]
Wie wäre es, die Voraussetzungen unter das Bild zu verschieben? Die Kursbeschreibung könnte sich dann über die restlichen 2/3 der Seite erstrecken.

Kann so im CSS nicht gelöst werden, da die Sidebar ein eigener Block ist

**Comment by CGreweling** [comment]
@luniki Du hattest doch letzen Donnerstag eine schöne Lösung...

**Comment by luniki** [comment]
Also die Voraussetzung muss ja schon ziemlich prominent platziert sein. Wieviel Text wird denn dieser Bereich beinhalten?

**Comment by CGreweling** [comment]
Hier ein Beispiel mehr wird es wohl nicht werden.
![bildschirmfoto vom 2015-03-03 10 29 53](https://cloud.githubusercontent.com/assets/3499600/6459591/549d9630-c190-11e4-970c-cd328349dde5.png)

**Comment by luhcas** [comment]
Ist erledigt, oder?!
