### ISSUE TITLE
Registrierungsseite Layout

### ISSUE THREAD

**Issue by CGreweling** [virtUOS/studip-ohn#61]
Abstände zu klein
Schriftgrößen uneinheitlich
Fenstertitel ist falsch (- Mooc.IP) - müsste der Kursname sein
Wenn ich mich registriert habe und dann auf der Folgeseite mein zugesandtes Passwort eingeben, komme ich nicht wie erwartet in den Kurs (oder aufs Dashboard?), sondern auf die Startseite und bin nicht angemeldet
Falsche Platzierung des Hinweises "Dies ist ein erforderliches Feld" (hidden?)

**Comment by luhcas** [comment]
Abstände und Schriftgrößen korrigiert.
