### ISSUE TITLE
Https 

### ISSUE THREAD

**Issue by CGreweling** [virtUOS/studip-ohn#7]
Zertifikat
Reverseproxy einrichten

**Comment by CGreweling** [comment]
Emke Fragen...

**Comment by lkiesow** [comment]
Gefragt. Wurde weitergegeben an Werbeagentur.

**Comment by lkiesow** [comment]
Zertikikate sind vorhanden.

**Comment by lkiesow** [comment]
HTTPS ist fertig konfiguriert.
Um es jetzt schon zu testen in `/etc/hosts` eintragen:

```
131.173.22.126  ohn-kursportal.de
```
