### ISSUE TITLE
Wysiwyg Editor Fromatierungs-Overlay verschoben

### ISSUE THREAD

**Issue by CGreweling** [virtUOS/studip-ohn#75]
Wenn ein Block länger als eine Bildschirmseite ist und man Text Formatiert z.B. Überschrift oder Eigenschaften eines Bildes:
Springt die Darstellung auf den Anfang der Seite und das Formatierungsoverlay "schwebt" über der Seite.

**Comment by zabbarob** [comment]
Ich vermute du meinst mit dem "Formatierungsoverlay" die Toolbar? Kannst du mir noch mehr Infos geben, da das Problem ja nicht grundsätzlich immer Auftritt:

Es gab schonmal einen Fehler dass wenn die Länge der Browserseite ziemlich genau der Länge des Browserfensters entspricht derartige "seltsame" Effekte auftreten. Das Problem war damal, dass sich durch das "rauspoppen" der Toolbar die Bildschirmseite verkürzt hat, wodurch die Seite gerade eben so wieder in das Browserfenster passte, wodurch die Toolbar wieder "zurückpoppte" und die Browserseite wieder etwas länger wurde, so dass sie gerade so nichtmehr in das Browserfenster passte... usw.usf. ...

Hört sich für mich hier ähnlich an: Durch die Formatierung als Überschrift wird die Browserseite ein klein wenig länger, so dass sie evtl. gerade so nicht mehr auf die Seite passt und dann könnte ich mir vorstellen bringt das die Offsetberechnung des Scrollbereichs evtl durcheinander wenn z.b. die Toolbar dann gerade so rausgepoppt wird...

Screenshot vom Fehlerzustand wäre noch super!!

**Comment by zabbarob** [comment]
Trac-Ticket dazu - http://develop.studip.de/trac/ticket/5425

**Comment by CGreweling** [comment]
![image](https://cloud.githubusercontent.com/assets/3499600/6688213/f47a8fe2-ccb1-11e4-960f-95a2ad9f2cfc.png)
--Wenn man versucht den Schrftstiel zu ändern:
![image](https://cloud.githubusercontent.com/assets/3499600/6688238/201792d0-ccb2-11e4-8b14-f29c4ffdc2ab.png)

Wie man sieht poppt das auswahlmenü raus und springt zum Anfang der Seite.
Das gleiche passiert beim editieren von Bildern.

**Comment by zabbarob** [comment]
haben das ja gerade besprochen :-), aber der vollständigkeit halber nochmal hier:

Das "rauspoppen" des Auswahlmenüs ist ein Fehler vom CKEditor. Wenn solche Dropdowns in der Toolbar geöffnet werden und man danach die Webseite wegscrollt bleiben diese einfach stehen.

Das eigentliche Problem ist also, dass die Seite weggescrollt wird. Warum das passiert ist mir im Augenblick nicht klar.

Der Webbrowser sollte nur scrollen nach Nutzereingabe oder wenn die Seitenlänge sich ändert, bzw. nur wenn sie kürzer wird - um nicht den "leeren" Bereich unter der Seite anzuzeigen. Aber vielleicht gibt es da noch andere Gründe warum er anfängt zu scrollen oder an den Seitenanfang springt. 

Ein Scrollen kann aber auch durch JavaScript verursacht werden und ich vermute, dass hier irgendwie das Zusammenspiel zwischen dem Wysiwyg-Block der MoocIP-Seite und dem CKEditor nicht tut und dann entweder Mooc.IP oder der CKEditor, bzw. unser Wysiwyg-Code, das scrollen initiiert.

Wichtig ist diesbezüglich noch, dass die Editorkomponente gerade als IFrame eingebunden ist. Ich habe allerdings seit längerem auf der TODO-Liste, die Einbindung als Div-Element zu machen. Dadurch ändern sich dann auch ein paar Sachen bzgl. der Handhabung der Toolbar, was sich wiederum evtl. auf den Effekt den wir hier beobachten auswirken kann.

Die Div-Einbindung werde ich wohl in den nächsten 2-3 Wochen machen. Es wäre dann sinnvoll, das auf die Stud.IP 3.1 zurückzuportieren und sich dann erst diesen Fehler hier anzuschauen.

**Comment by CGreweling** [comment]
Wie könnte ich das jetzt für unsere OHN Mooc.ip installation lösen? Eine Idee?

**Comment by zabbarob** [comment]
Am einfachsten wäre es, die schwebende Toolbar zu disablen. Das ist dann zwar bei längeren Texten umständlich, aber würde erstmal dafür sorgen, dass der Fehler nicht ausgelöst werden kann. (wenn's denn daran liegt). 

Dazu in der Datei `public/assets/javascripts/wysiwyg.js` im folgenden Code-Block den Aufruf von `updateStickyTools` auskommentieren (ab ungefähr [Zelle 417](https://develop.studip.de/trac/browser/trunk/public/assets/javascripts/wysiwyg.js?rev=33657#L417), je nach Revision):

```
// do not scroll toolbar out of viewport
function stickyTools() {
    updateStickyTools(editor);
};
$(window).scroll(stickyTools);
$(window).resize(stickyTools);
editor.on('focus', stickyTools); // hidden toolbar might scroll off screen
```

**Comment by zabbarob** [comment]
ps: mit der Div-Einbindung wird's wohl noch bissl dauern, bin gerade noch an anderen Sachen drann...

**Comment by tthelen** [comment]
Wie sieht's aus? Gibt es etwas Neues?

**Comment by CGreweling** [comment]
@zabbarob deine Tips "ab Zeile 417 auskommentieren" haben leider nichts gebracht

**Comment by zabbarob** [comment]
interessant, dann liegt's jedenfalls nicht an der schwebenden toolbar, vermutlich würde dann auch die umstellung von iframe auf div nix bringen. m.a.W. muss ich mir im detail anschauen was da passiert. am besten du gibst da auch nochmal elmar bescheid, da er mir ja die arbeitspakete zuweist, ansonsten bin ich nämlich gerade in die wysiwyg-umstellung (trennung von studip-markup) eingebunden.

**Comment by zabbarob** [comment]
Elmar und ich haben das gerade bei uns im Testsystem ausprobiert. Dort tritt der Fehler (leider?) nicht auf... Denke wir müssen uns das in der OHN-Testinstallation nochmal anschauen. Kontaktiere mich da am besten nochmal per PM, vielleicht mit Zugangsdaten und Link auf die Seite.

**Comment by CGreweling** [comment]
ist wieder OK
