### ISSUE TITLE
Text hat zu wenig Abstand wenn er neben dem Bild steht

### ISSUE THREAD

**Issue by CGreweling** [virtUOS/studip-ohn#78]
Bei einem Bild mit Float left ist kein Abstand zwischen Bild und Text.

**Comment by zabbarob** [comment]
Breite des Rands sollte m.M.n. im Grundlegenden Stud.IP-CSS definiert werden. Also evtl. könnt ihr das CSS dann quasi an der Basis updaten ;-)

**Comment by luhcas** [comment]
Wie wird das nun gelöst?

**Comment by CGreweling** [comment]
Entweder Du schreibts das in das OHN-Plugin oder einfach in das css von studip
und kopierst, die entsprechende Zeile hier hin, da pflegen wir das ein.
Was für Dich am besten funktioniert.

**Comment by luhcas** [comment]
ist im OHN-Plugin gelöst
