### ISSUE TITLE
Zuordnungsaufgaben sind verrückt wenn Teile mehrzeilig sind

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/studip-ohn#79]
![zuordnungsaufgabe](https://cloud.githubusercontent.com/assets/1008395/6900356/3ccd0c26-d706-11e4-8a1f-4e5d91111073.png)

Schwierig zuzuordnen, wenn die Blöcke unterschiedlich hoch sind…

**Comment by lkiesow** [comment]
Noch weiter verrückt ist es, wenn Antworten hinzu kommen:

![zuordnungsaufgabe-antworten](https://cloud.githubusercontent.com/assets/1008395/6900441/bf44e2e6-d706-11e4-987b-80695d052622.png)

**Comment by luniki** [comment]
Bin dran, gestaltet sich aber als eher schwierig.

**Comment by luniki** [comment]
@lkiesow Schau bitte einmal, ob es jetzt besser passt.

**Comment by lkiesow** [comment]
Leider nein.

Bücherdschungel -> Sichten, sortieren, bewerten -> Textformen I

![zoo](https://cloud.githubusercontent.com/assets/1008395/8405493/2f2138e0-1e55-11e5-9e54-ded94e6a7151.png)

**Comment by luniki** [comment]
Das ist kein Problem von Mooc.IP, sondern wird vom OHNLayout-Plugin ausgelöst. Die folgende Regel führt dazu:

foundation.css:

_,_:before,_:after {
  -moz-box-sizing: border-box;
  /_ -webkit-box-sizing: border-box; _/
  /_ box-sizing: border-box; */
}

**Comment by lkiesow** [comment]
Vorsichtig nachgefragt: Passiert irgendetwas böses mit dem Layout, wenn man die Regel entfernt? Oder könnte man die einfach rauswerfen?

**Comment by CGreweling** [comment]
@lkoehler können wir das entfernen?

**Comment by luhcas** [comment]
Nicht entfernen aber korrigieren
