### ISSUE TITLE
Zeilenumbruch in Lückentexten

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/studip-ohn#80]
Zeilenumbruch in Lückentexten wird ignoriert

Probiert:
- Einfacher Umbruch
- Mehrfacher Umbruch
- HTML eingefügt

![zeilenumbruch-im-lueckentext](https://cloud.githubusercontent.com/assets/1008395/6900883/e5886dc6-d709-11e4-92b8-9bb67b107bd0.png)

**Comment by lkiesow** [comment]
Zeilenumbrüche werden scheinbar nicht ignoriert wenn die Zeile mit einem non-breaking endet… verrückt…

**Comment by lkiesow** [comment]
Hat leider nur bei einer Aufgabe funktioniert. Bei der abgebildeten nicht.

**Comment by lkiesow** [comment]
Andere Aufgaben sind auch berichtigt. Aber immer noch mit nbsp. Muss noch ordentlich gefixt werden

**Comment by lkiesow** [comment]
Funktioniert leider nicht nach dem Abschicken:

![zeilenumbruch](https://cloud.githubusercontent.com/assets/1008395/8435852/3d0568d2-1f54-11e5-9d2e-e2d0b2e4557c.png)

**Comment by luniki** [comment]
fixed in virtUOS/mooc.ip
