### ISSUE TITLE
Sonderzeichenfehler bei Freitextfeld

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/studip-ohn#81]
![sonderzeichenfehler-a](https://cloud.githubusercontent.com/assets/1008395/6902713/bfa5bac6-d715-11e4-88c9-3dfeb22f8361.png)

![sonderzeichenfehler-b](https://cloud.githubusercontent.com/assets/1008395/6902718/c3aa4c4a-d715-11e4-99f9-e2c264bcd406.png)

![sonderzeichenfehler-c](https://cloud.githubusercontent.com/assets/1008395/6902720/c79446c6-d715-11e4-9a49-dd25b828dfed.png)

Wie man sieht wird das Sonderzeichen richtig eingetragen. Nacher wird es aber falsch dargestellt, die Aufgabe ist daher auch falsch beantwortet und die Aufgabe bzw. Antwort schiebt sich über den Rand

**Comment by lkiesow** [comment]
Zu finden unter Handwerkszeug... -> wer hat's GEDACHT... -> richtig zitieren

**Comment by CGreweling** [comment]
Die Aufgabe lässt sich auch in der Vips Vorschau nicht richtig lösen.

**Comment by CGreweling** [comment]
return htmlspecialchars($string, ENT_COMPAT, 'cp1252');
Muss das ganze von der courseware seite aus encodiert werden?

**Comment by tgloeggl** [comment]
allow umlaute and special characters as vips-cloze_answers 
https://github.com/virtUOS/mooc.ip/commit/a430aace39c494212a5765534380d6e931fd94a3
