### ISSUE TITLE
Andere Schriftart für Latex-Code

### ISSUE THREAD

**Issue by CGreweling** [virtUOS/studip-ohn#82]
Indizies werden in der Verwendeten Schriftart nicht korrekt dargestellt.
Ist es möglich hierfür eine eigene Schriftart zu hinterlegen?

![](imap://greweling@h1343127.stratoserver.net:143/fetch%3EUID%3E/INBOX%3E548?header=quotebody&part=1.1.2.2&filename=neue_variante.png)

**Comment by luniki** [comment]
Da sollte man hier mal schauen: http://docs.mathjax.org/en/latest/font-support.html
