### ISSUE TITLE
"News FAQ" Reiter Schriftart und Schriftgröße anpassen

### ISSUE THREAD

**Issue by CGreweling** [virtUOS/studip-ohn#91]
das ist so zu klein. Beispiel Kurs vom Beruf ins Studium
Ein
imap://greweling@h1343127.stratoserver.net:143/fetch%3EUID%3E/INBOX%3E580?part=1.2.5&filename=Woche1-Kap1-Seite3-%2001.PNG

imap://greweling@h1343127.stratoserver.net:143/fetch%3EUID%3E/INBOX%3E580?part=1.2.4&filename=Woche1-Kap1-Seite1-%2002.PNG

**Comment by luhcas** [comment]
Kann ich nicht finden und die Screenshots werden nicht angezeigt. Kannst du vielleicht noch ein Foto zeigen?

**Comment by CGreweling** [comment]
Beispiel Kurs: Vom Beruf ins Studium
Das ist der offizielle Reite "Freie Informatuonsseite" 
Der hier Nwes/FAQ heisst
