### ISSUE TITLE
Phpmyadmin auf Server installieren

### ISSUE THREAD

**Issue by CGreweling** [virtUOS/studip-ohn#95]
Bitte auf dem Server PHPmyadmin installieren für Tobias.

**Comment by tthelen** [comment]
adminer-Plugin installieren

**Comment by tgloeggl** [comment]
Das Adminer-Plugin ist eventuell doch nicht die beste Idee. Wir sollten einfach ein Verzeichnis auf dem Server erstellen und den Adminer dort reinlegen.

EDIT: Habe ich jetzt gemacht: https://ohn-kursportal.de/adminer/
Hab erstmal eine .htaccess davorgepackt, die das auf den virtUOS-IP-Bereich einschränkt. Sollte da eventuell besser ne Passwortabfrage hin?

Im Moment wird die .htaccess-Datei allerdings noch nicht ausgewertet, am Besten man packt das in eine Apache-Config-Datei. Solange das nicht passiert ist, steht am Anfang von Adminer ein "die;" ;)

**Comment by lkiesow** [comment]
phpmyadmin ist installiert: https://.../phpmyadmin

Erreichbar nur aus dem virtUOS-Netz
