### ISSUE TITLE
„Registrieren“-Hinweis auf Anmeldeseite

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/studip-ohn#96]
Es ist unklar wie man sich für die Plattform registriert. Es sollte auf der Anmelden-Seite zumindest eine kurze Erklärung geben:

```
<div style="float: right; width: 250px;">
<p>Sie haben noch keinen Account?<br /><br />
<span style="font-size: smaller;"><a href="<?= URLHelper::getUrl('plugins.php/mooc/courses/index') ?>">Registrieren Sie sich zun&auml;chst f&uuml;r einen Kurs um einen Account zu erhalten.</a></span></p>
</div>
```

**Comment by CGreweling** [comment]
@luniki  kriegen wir das irgendwie hier in das plugin rein?

**Comment by tthelen** [comment]
s. #99

**Comment by CGreweling** [comment]
verweißt leider noch auf den falschen Link
das müsste hier hin
plugins.php/mooc/courses/index
wenn ich das hier ersetzte wird der Link aber nicht geöffnet..?

**Comment by CGreweling** [comment]
/mooc/courses/index?cancel_login=1
