### ISSUE TITLE
Pseudonym einfügen?

### ISSUE THREAD

**Issue by CGreweling** [virtUOS/studip-ohn#97]
Momentan heisst das Feld "Vollständiger Name"  

Dies sollte anders benannt werden und der Inhalt in evtl. in das Feld Vorname geschrieben.
Damit dieser z.B. im Forum auftaucht?

**Comment by tthelen** [comment]
Ich habe die Lage bislang so verstanden:
- Die Nutzer können ein Pseudonym wählen, das dann an Forenbeiträgen usw. zu sehen ist. Dafür sind in Stud.IP die Felder Vorname und Nachname in der Tabelle auth_user_md5 vorgesehen.
- Für eventuelle Zertifikate etc. benötigt man auch den vollständigen korrekten Namen. Der wird in einem neuen Datenfeld mit dem Namen "Vollständiger Name" abgelegt.

Aus meiner Sicht müsste also bei der Registrierung ein Pseudonym mit angegeben werden können, bestehend aus Vorname und Nachname (Vorname optional)

**Comment by tthelen** [comment]
s. #102
